name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - pip
  - jupyterlab
  - matplotlib-base
  - numpy
  - pandas
  - pip:
    - poetry
    # Additional packages will be managed by Poetry
    # See pyproject.toml for dependencies