name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - pip
  # Note: Additional conda dependencies will be added by the post-generation hook
  # based on the user's selections
  - pip:
    - poetry
    # Additional packages will be managed by Poetry
    # See pyproject.toml for dependencies